spring.application.name=SpringEcom

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/Krushna

spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.auto-commit=false